version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.492
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CORS_ALLOW_ORIGIN=*
      # Uncomment the line below and replace with your app URL if needed
      # - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CORS_ALLOW_ORIGIN=https://deine-app-url.de

    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8082:8082"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local

#8c092d9e5d9f45d0b03b4d2eb0d2029f